version: '3.3'
services:
  db:
    image: postgres
    ports:
      - 15432:5432
    volumes:
      - /home/ftiburcio/Desktop/PESSOAL/PROJETOS/volume:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=1234
    networks:
      - development-network
  app:
    image: dpage/pgadmin4
    links:
      - db:db
    ports:
      - 16543:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "felipeconceicaolopes@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "@Madara1994"
    depends_on:
      - db
    networks:
      - development-network
networks:
 development-network:
   driver: bridge
