apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset-postgres
spec:
  serviceName: db
  template:
    metadata:
      labels:
       name: postgres
    spec:
      containers:
        - name: container-postgres
          image: postgres:11.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "contatos"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "1234"
          volumeMounts:
            - name: volume-postgres
              mountPath: /var/lib/postgresql
      volumes:
        - name: volume-postgres
          persistentVolumeClaim:
            claimName: config-postgres